on:
  push:
    branches: [ android-app ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Checkout python-for-android fix
        run: |
          git clone https://github.com/kivy/python-for-android.git python-for-android
          cd python-for-android
          git checkout d2ee8c54d9d42375a95f18159e950a119671cf63

      - name: Install python-for-android dependencies
        run: python3 -m pip install -e ./python-for-android

      - name: Build APK
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.11
          buildozer-cmd: buildozer android clean && buildozer -v android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./bin/*.apk
